version: '3'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: gitlab-prod
#     hostname: "gitlab"
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'http://git.dorgam.it/'
#        gitlab_rails['gitlab_shell_ssh_port'] = 22
#        gitlab_rails['lfs_enabled'] = true
#        nginx['listen_port'] = 8081
    ports:
      - "80:80"
      - "4443:443"
      - "2222:22"

    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    networks:
      - devops

networks:
  devops:
    driver: bridge

